FROM node:18.17 AS node-base
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install postgresql -y

FROM node-base AS install-base
WORKDIR /app
ADD package.json /app
RUN yarn install

FROM install-base AS development
ADD .eslintrc.cjs index.html tsconfig.json tsconfig.node.json vite.config.ts /app
ADD src /app/src
CMD yarn dev
